export const siteConfig = {
  name: "PDF Pro",
  shortName: "PDF Pro",
  description: "Bộ công cụ xử lý PDF trực tuyến miễn phí, tiếng Việt, nhanh chóng và bảo mật 100%. File không bao giờ tải lên máy chủ, xử lý an toàn ngay trên trình duyệt của bạn.",
  url: "https://pdf-pro-omega.vercel.app",
  ogImage: "https://pdf-pro-omega.vercel.app/og.jpg",
  contactEmail: "hotro@pdfpro.vn",
  creator: "PDF Pro Team",
  keywords: [
    "pdf pro",
    "công cụ pdf miễn phí",
    "ghép pdf",
    "tách pdf",
    "nén pdf",
    "xoay pdf",
    "chuyển ảnh sang pdf",
    "pdf sang ảnh",
    "đánh số trang pdf",
    "đóng dấu watermark pdf",
    "xử lý pdf không cần tải lên",
    "pdf bảo mật tiếng việt",
  ],
  navItems: [
    { label: "Trang chủ", href: "/" },
    { label: "Tất cả công cụ", href: "/tat-ca-cong-cu" },
    { label: "Ghép PDF", href: "/ghep-file-pdf" },
    { label: "Tách PDF", href: "/tach-file-pdf" },
    { label: "Nén PDF", href: "/nen-file-pdf" },
    { label: "Chuyển ảnh sang PDF", href: "/anh-sang-pdf" },
    { label: "Giới thiệu", href: "/gioi-thieu" },
  ],
  footerLinks: {
    tools: [
      { label: "Ghép file PDF", href: "/ghep-file-pdf" },
      { label: "Tách file PDF", href: "/tach-file-pdf" },
      { label: "Nén file PDF", href: "/nen-file-pdf" },
      { label: "Xoay file PDF", href: "/xoay-pdf" },
      { label: "Xóa trang PDF", href: "/xoa-trang-pdf" },
      { label: "Sắp xếp trang PDF", href: "/sap-xep-trang-pdf" },
      { label: "Ảnh sang PDF", href: "/anh-sang-pdf" },
      { label: "PDF sang ảnh", href: "/pdf-sang-anh" },
      { label: "Chèn số trang", href: "/chen-so-trang" },
      { label: "Thêm Watermark", href: "/them-watermark" },
    ],
    about: [
      { label: "Về PDF Pro", href: "/gioi-thieu" },
      { label: "Chính sách bảo mật", href: "/chinh-sach-bao-mat" },
      { label: "Điều khoản sử dụng", href: "/dieu-khoan-su-dung" },
      { label: "Liên hệ & Góp ý", href: "/lien-he" },
      { label: "Sơ đồ trang", href: "/sitemap.xml" },
    ],
  },
};
